# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 20:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersavedalbum',
            name='album',
        ),
        migrations.RemoveField(
            model_name='usersavedalbum',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='usersavedplaylist',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='usersavedplaylist',
            name='playlist',
        ),
        migrations.AddField(
            model_name='album',
            name='savedBy',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='savedBy',
            field=models.ManyToManyField(related_name='savedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='songLength',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='lastPlayed',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='UserSavedAlbum',
        ),
        migrations.DeleteModel(
            name='UserSavedPlaylist',
        ),
    ]
