# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_playlist_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(default='/media/1.jpg', upload_to=''),
        ),
    ]
