# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_remove_playlist_savedby'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-timeAdded']},
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='lastPlayed',
            new_name='timeAdded',
        ),
    ]
